const User = require("../models/userModel");
const Trip = require("../models/tripModel");
const TripRequest = require("../models/tripRequestModel");
const TripMatch = require("../models/tripMatchModel");
const { uploadToCloudinary, deleteFromCloudinary } = require("../utils/fileUpload");

const AppError = require("../utils/AppError");
const catchAsync = require("../utils/catchAsync");

  exports.createTripReq = catchAsync(async (req, res, next) => {
    // Parse data from FormData or JSON
    let user, destination, destinationType, date, time, genderPreference;
    let startLocation, destinationLocation, routeCoordinates, transportMode;
    const searchDuration = 2 * 60 * 1000; // Default 2 minutes
    
    // Check if request contains file (FormData) or is JSON
    if (req.file || req.files) {
      // FormData request - parse JSON fields
      user = req.body.user ? JSON.parse(req.body.user) : null;
      destination = req.body.destination;
      destinationType = req.body.destinationType;
      date = req.body.date;
      time = req.body.time;
      genderPreference = req.body.genderPreference;
      startLocation = req.body.startLocation ? JSON.parse(req.body.startLocation) : null;
      destinationLocation = req.body.destinationLocation ? JSON.parse(req.body.destinationLocation) : null;
      routeCoordinates = req.body.routeCoordinates ? JSON.parse(req.body.routeCoordinates) : [];
      transportMode = req.body.transportMode;
    } else {
      // JSON request
      ({
        user, 
        destination, 
        destinationType, 
        date, 
        time, 
        genderPreference,
        startLocation,
        destinationLocation,
        routeCoordinates,
        transportMode
      } = req.body);
    }
  
    if (!user || !user.userName) {
      return next(new AppError("User name is required", 400));
    }
  
    // Find user by userName
    const existingUser = await User.findOne({ userName: user.userName });
    if (!existingUser) {
      return next(new AppError("User not found", 404));
    }
  
    // Generate trip request ID
    const tripReqId = existingUser.userName.slice(0, 3).toUpperCase() + Date.now();

    // Debug logging
    console.log('🔍 [CREATE TRIP] Start location received:', JSON.stringify(startLocation, null, 2));

    // Create new TripRequest using full user data
    const newTripRequest = await TripRequest.create({
      tripReqId,
      user: {
        userId: existingUser._id.toString(),
        userName: existingUser.userName,
        userImage: existingUser.profilePhoto?.url || "default.jpg"
      },
      startLocation, // Persist sender-selected meeting point
      destination,
      destinationType,
      date,
      time,
      genderPreference,
      destinationLocation,
      routeCoordinates: routeCoordinates || [],
      transportMode,
      searchDuration,
      expiresAt: new Date(Date.now() + searchDuration),
      // Automatically set meeting point to sender's starting location
      meetingPoint: {
        latitude: startLocation?.latitude,
        longitude: startLocation?.longitude,
        address: startLocation?.address,
        name: startLocation?.address || "Starting Point",
        description: "Sender's starting location",
        type: "starting_point",
        isAutoGenerated: true
      },
      consent: {
        senderConsent: true, // Set when sender completes consent form
        noTouchAgreed: false,
        receiverConsent: false
      }
    });

    // ⚠️ REMOVED AUTO-DISTRIBUTE: Trip request will be sent to nearby users manually
    // after sender completes the full flow (consent → photo → preferences)
    // This prevents receivers from seeing incomplete/updating trip information
    console.log('📋 [CREATE TRIP] Trip request created successfully (not yet distributed)');
    console.log('📋 [CREATE TRIP] Waiting for sender to complete photo and preferences...');
  
    // Upload photo if provided (FormData request)
    if (req.file) {
      console.log('📸 [CREATE TRIP] Photo provided, uploading to Cloudinary...');
      try {
        const uploadResult = await uploadToCloudinary(
          req.file,
          "trip-photos",
          existingUser._id.toString()
        );
        newTripRequest.photo = uploadResult;
        await newTripRequest.save();
        console.log('✅ [CREATE TRIP] Photo uploaded:', uploadResult.url);
      } catch (uploadError) {
        console.error('❌ [CREATE TRIP] Photo upload failed:', uploadError);
        // Don't fail the request, just continue without photo
      }
    }
  
    res.status(201).json({
      status: "success",
      data: {
        tripRequest: newTripRequest,
      },
    });
  });  

  
exports.createTrip = catchAsync(async (req, res, next) => {
  const { user, companion, consent, distanceMaintained, distancePreferred, genderPreference, imageVerification } = req.body;

  if (!user?.userName || !companion?.userName) {
    return next(new AppError("Both user and companion usernames are required", 400));
  }

  // Find user and companion by username
  const existingUser = await User.findOne({ userName: user.userName });
  if (!existingUser) return next(new AppError("User not found", 404));

  const existingCompanion = await User.findOne({ userName: companion.userName });
  if (!existingCompanion) return next(new AppError("Companion not found", 404));

  // Generate unique trip ID
  const tripId = existingUser.userName.slice(0, 3).toUpperCase() + existingCompanion.userName.slice(0, 3).toUpperCase() + Date.now();

  // Create trip
  const newTrip = await Trip.create({
    tripId,
    user: {
      userId: existingUser._id.toString(),
      userName: existingUser.userName,
      userImage: existingUser.profilePhoto?.url || "default.jpg"
    },
    companion: {
      userId: existingCompanion._id.toString(),
      userName: existingCompanion.userName,
      userImage: existingCompanion.profilePhoto?.url || "default.jpg"
    },
    consent,
    distanceMaintained,
    distancePreferred,
    genderPreference,
    imageVerification
  });

  res.status(201).json({
    status: "success",
    data: {
      trip: newTrip
    }
  });
});

// Update trip request with route and location data
exports.updateTripRequest = catchAsync(async (req, res, next) => {
  const { tripReqId } = req.params;
  const updateData = req.body;

  console.log('🔄 [UPDATE TRIP] Updating trip request:', tripReqId);
  console.log('🔄 [UPDATE TRIP] Update data:', JSON.stringify(updateData, null, 2));

  const tripRequest = await TripRequest.findOneAndUpdate(
    { tripReqId },
    updateData,
    { new: true, runValidators: true }
  );

  if (!tripRequest) {
    console.log('❌ [UPDATE TRIP] Trip request not found:', tripReqId);
    return next(new AppError("Trip request not found", 404));
  }

  console.log('✅ [UPDATE TRIP] Trip request updated successfully');
  console.log('📍 [UPDATE TRIP] Updated route data:', {
    destination: tripRequest.destination,
    destinationType: tripRequest.destinationType,
    hasStartLocation: !!tripRequest.startLocation,
    hasDestinationLocation: !!tripRequest.destinationLocation,
    routeCoordinatesCount: tripRequest.routeCoordinates?.length || 0,
    transportMode: tripRequest.transportMode
  });

  res.status(200).json({
    status: "success",
    data: {
      tripRequest
    }
  });
});

// Set meeting point for trip request
exports.setMeetingPoint = catchAsync(async (req, res, next) => {
  const { tripReqId } = req.params;
  const { meetingPoint } = req.body;

  const tripRequest = await TripRequest.findOneAndUpdate(
    { tripReqId },
    { 
      meetingPoint: {
        ...meetingPoint,
        isSelected: true
      }
    },
    { new: true }
  );

  if (!tripRequest) {
    return next(new AppError("Trip request not found", 404));
  }

  res.status(200).json({
    status: "success",
    data: {
      tripRequest
    }
  });
});

// Complete consent form for receiver
exports.completeReceiverConsent = catchAsync(async (req, res, next) => {
  const { tripReqId } = req.params;
  const { userId } = req.body;

  const tripRequest = await TripRequest.findOneAndUpdate(
    { tripReqId },
    { 
      'consent.receiverConsent': true,
      'consent.noTouchAgreed': true,
      'consent.consentCompletedAt': new Date()
    },
    { new: true }
  );

  if (!tripRequest) {
    return next(new AppError("Trip request not found", 404));
  }

  res.status(200).json({
    status: "success",
    message: "Consent completed successfully",
    data: {
      tripRequest
    }
  });
});

// Get active trip request for user (to maintain persistent search)
exports.getActiveRequest = catchAsync(async (req, res, next) => {
  const userId = req.user.id;

  const activeRequest = await TripRequest.findOne({
    'user.userId': userId,
    status: 'pending',
    expiresAt: { $gt: new Date() }
  });

  res.status(200).json({
    status: "success",
    data: {
      activeRequest
    }
  });
});

exports.getTripReq = catchAsync(async (req, res, next) => {
    const { tripReqId } = req.body;

    if (!tripReqId) {
        return next(new AppError("Trip Request ID is required", 400));
    }

    const tripRequest = await TripRequest.findOne({ tripReqId });

    if (!tripRequest) {
        return next(new AppError("Trip Request not found", 404));
    }

    res.status(200).json({
        status: "success",
        data: {
            tripRequest,
        },
    });
});

exports.getTrip = catchAsync(async (req, res, next) => {
    const { tripId } = req.body;

    if (!tripId) {
        return next(new AppError("Trip ID is required", 400));
    }

    const trip = await Trip.findOne({ tripId });

    if (!trip) {
        return next(new AppError("Trip not found", 404));
    }

    res.status(200).json({
        status: "success",
        data: {
            trip,
        },
    });
});

exports.uploadTripPhoto = catchAsync(async (req, res, next) => {
  if (!req.file) {
    return next(new AppError("No file uploaded", 400));
  }

  const { tripReqId } = req.params;
  if (!tripReqId) {
    return next(new AppError("Trip Request ID is required", 400));
  }

  const tripRequest = await TripRequest.findOne({ tripReqId });
  if (!tripRequest) {
    return next(new AppError("Trip Request not found", 404));
  }

  // Delete existing photo if any
  if (tripRequest.photo?.publicId) {
    await deleteFromCloudinary(tripRequest.photo.publicId);
  }

  // Upload new photo
  const uploadResult = await uploadToCloudinary(
    req.file,
    "trip-photos",
    tripRequest.user.userId
  );

  // Update trip request with new photo
  tripRequest.photo = uploadResult;
  await tripRequest.save();

  res.status(200).json({
    status: "success",
    message: "Photo uploaded successfully",
    data: {
      photoUrl: uploadResult.url
    }
  });
});

exports.updateTripRequestBasic = catchAsync(async (req, res, next) => {
  const { tripReqId } = req.params;
  const { destination, destinationType, date, time, genderPreference } = req.body;

  if (!tripReqId) {
    return next(new AppError("Trip Request ID is required", 400));
  }

  const tripRequest = await TripRequest.findOne({ tripReqId });
  if (!tripRequest) {
    return next(new AppError("Trip Request not found", 404));
  }

  // Update fields if provided
  if (destination) tripRequest.destination = destination;
  if (destinationType) tripRequest.destinationType = destinationType;
  if (date) tripRequest.date = date;
  if (time) tripRequest.time = time;
  if (genderPreference) tripRequest.genderPreference = genderPreference;

  await tripRequest.save();

  res.status(200).json({
    status: "success",
    message: "Trip request updated successfully",
    data: {
      tripRequest
    }
  });
});

exports.markArrived = catchAsync(async (req, res, next) => {
  const { requestId } = req.body;
  const userId = req.user._id.toString();

  if (!requestId) {
    return next(new AppError("Request ID is required", 400));
  }

  const tripRequest = await TripRequest.findById(requestId);
  if (!tripRequest) {
    return next(new AppError("Trip request not found", 404));
  }

  // Initialize arrivedUsers array if it doesn't exist
  if (!tripRequest.arrivedUsers) {
    tripRequest.arrivedUsers = [];
  }

  // Check if user already marked as arrived
  if (tripRequest.arrivedUsers.includes(userId)) {
    return res.status(200).json({
      status: "success",
      message: "Already marked as arrived"
    });
  }

  // Add user to arrived list
  tripRequest.arrivedUsers.push(userId);

  // Check if both users have arrived (sender and receiver)
  const allUsersArrived = tripRequest.arrivedUsers.includes(tripRequest.user.userId) && 
                          tripRequest.receiverConsent && 
                          tripRequest.arrivedUsers.includes(tripRequest.receiverConsent.receiverId);

  if (allUsersArrived) {
    tripRequest.canStartFinalJourney = true;
  }

  await tripRequest.save();

  res.status(200).json({
    status: "success",
    message: allUsersArrived ? "Both users arrived! Ready to start final journey." : "Arrival marked successfully",
    data: {
      arrivedUsers: tripRequest.arrivedUsers,
      canStartFinalJourney: tripRequest.canStartFinalJourney
    }
  });
});

exports.startTrip = catchAsync(async (req, res, next) => {
  const { requestId } = req.body;
  const userId = req.user._id.toString();

  if (!requestId) {
    return next(new AppError("Request ID is required", 400));
  }

  const tripRequest = await TripRequest.findById(requestId);
  if (!tripRequest) {
    return next(new AppError("Trip request not found", 404));
  }

  // Initialize startedUsers array if it doesn't exist
  if (!tripRequest.startedUsers) {
    tripRequest.startedUsers = [];
  }

  // Check if user already marked as started
  if (tripRequest.startedUsers.includes(userId)) {
    return res.status(200).json({
      status: "success",
      message: "Already marked as started",
      data: { bothUsersReady: tripRequest.tripStarted }
    });
  }

  // Add user to started list
  tripRequest.startedUsers.push(userId);

  // Check if both users are ready to start (sender and receiver)
  const bothUsersReady = tripRequest.startedUsers.includes(tripRequest.user.userId) && 
                        tripRequest.receiverConsent && 
                        tripRequest.startedUsers.includes(tripRequest.receiverConsent.receiverId);

  if (bothUsersReady) {
    tripRequest.tripStarted = true;
    tripRequest.tripStartedAt = new Date();
  }

  await tripRequest.save();

  res.status(200).json({
    status: "success",
    message: bothUsersReady ? "Both users ready! Trip started!" : "Ready to start trip",
    data: {
      startedUsers: tripRequest.startedUsers,
      bothUsersReady: tripRequest.tripStarted
    }
  });
});

exports.cancelTrip = catchAsync(async (req, res, next) => {
  const { requestId } = req.body;
  const userId = req.user._id.toString();

  if (!requestId) {
    return next(new AppError("Request ID is required", 400));
  }

  const tripRequest = await TripRequest.findById(requestId);
  if (!tripRequest) {
    return next(new AppError("Trip request not found", 404));
  }

  // Check if user is part of this trip
  const isOrganizerOrCompanion = tripRequest.user.userId === userId || 
                                 (tripRequest.receiverConsent && tripRequest.receiverConsent.receiverId === userId);
  
  if (!isOrganizerOrCompanion) {
    return next(new AppError("You are not authorized to cancel this trip", 403));
  }

  // Update status to cancelled
  tripRequest.status = 'cancelled';
  tripRequest.cancelledBy = userId;
  tripRequest.cancelledAt = new Date();

  await tripRequest.save();

  res.status(200).json({
    status: "success",
    message: "Trip cancelled successfully"
  });
});

exports.endTrip = catchAsync(async (req, res, next) => {
  const { requestId } = req.body;
  const userId = req.user._id.toString();

  if (!requestId) {
    return next(new AppError("Request ID is required", 400));
  }

  const tripRequest = await TripRequest.findById(requestId);
  if (!tripRequest) {
    return next(new AppError("Trip request not found", 404));
  }

  // Check if user is part of this trip
  const isOrganizerOrCompanion = tripRequest.user.userId === userId || 
                                 (tripRequest.receiverConsent && tripRequest.receiverConsent.receiverId === userId);
  
  if (!isOrganizerOrCompanion) {
    return next(new AppError("You are not authorized to end this trip", 403));
  }

  // Update status to completed
  tripRequest.status = 'completed';
  tripRequest.completedAt = new Date();

  await tripRequest.save();

  res.status(200).json({
    status: "success",
    message: "Trip completed successfully"
  });
});

exports.expireRequest = catchAsync(async (req, res, next) => {
  const { tripReqId } = req.params;
  const userId = req.user._id.toString();

  if (!tripReqId) {
    return next(new AppError("Trip Request ID is required", 400));
  }

  const tripRequest = await TripRequest.findOne({ tripReqId });
  if (!tripRequest) {
    return next(new AppError("Trip request not found", 404));
  }

  // Only the sender can expire their own request
  if (tripRequest.user.userId !== userId) {
    return next(new AppError("You can only expire your own requests", 403));
  }

  // Only expire if still pending
  if (tripRequest.status === 'pending') {
    tripRequest.status = 'expired';
    await tripRequest.save();

    res.status(200).json({
      status: "success",
      message: "Trip request expired successfully"
    });
  } else {
    res.status(200).json({
      status: "success", 
      message: `Request already ${tripRequest.status}`
    });
  }
});

// Update arrival status for navigation
exports.updateArrival = catchAsync(async (req, res, next) => {
  const { matchId, userRole, arrivedAt } = req.body;
  const userId = req.user._id.toString();

  console.log(`🚶‍♀️ [ARRIVAL] User ${userId} (${userRole}) arrived at meeting point for match ${matchId}`);

  const TripMatch = require("../models/tripMatchModel");
  const tripMatch = await TripMatch.findOne({ matchId });
  
  if (!tripMatch) {
    return next(new AppError("Trip match not found", 404));
  }

  // Verify user is part of this match
  const isAuthorized = tripMatch.organizer.userId === userId || tripMatch.companion.userId === userId;
  if (!isAuthorized) {
    return next(new AppError("Not authorized for this trip match", 403));
  }

  // Update arrival status
  if (userRole === 'organizer') {
    tripMatch.progression.organizerArrived = new Date(arrivedAt);
  } else {
    tripMatch.progression.companionArrived = new Date(arrivedAt);
  }

  // If both arrived, mark as meeting
  if (tripMatch.progression.organizerArrived && tripMatch.progression.companionArrived) {
    tripMatch.status = 'meeting';
    console.log(`👥 [MEETING] Both users arrived for match ${matchId}`);
  }

  await tripMatch.save();

  res.status(200).json({
    status: "success",
    message: "Arrival updated successfully",
    data: {
      match: tripMatch
    }
  });
});

// Complete trip match
exports.completeMatch = catchAsync(async (req, res, next) => {
  const { matchId, completedBy } = req.body;
  const userId = req.user._id.toString();

  console.log(`✅ [COMPLETE] User ${userId} (${completedBy}) completing match ${matchId}`);

  const TripMatch = require("../models/tripMatchModel");
  const tripMatch = await TripMatch.findOne({ matchId });
  
  if (!tripMatch) {
    return next(new AppError("Trip match not found", 404));
  }

  // Verify user is part of this match
  const isAuthorized = tripMatch.organizer.userId === userId || tripMatch.companion.userId === userId;
  if (!isAuthorized) {
    return next(new AppError("Not authorized for this trip match", 403));
  }

  // Mark as completed
  tripMatch.status = 'completed';
  tripMatch.progression.completed = new Date();
  
  await tripMatch.save();

  // Also update the original trip request
  const tripRequest = await TripRequest.findOne({ tripReqId: tripMatch.originalTripRequest.tripReqId });
  if (tripRequest) {
    tripRequest.status = 'completed';
    tripRequest.completedAt = new Date();
    await tripRequest.save();
  }

  console.log(`🎉 [COMPLETED] Match ${matchId} successfully completed`);

  res.status(200).json({
    status: "success",
    message: "Trip completed successfully",
    data: {
      match: tripMatch
    }
  });
});

// ===== POST-ACCEPTANCE WORKFLOW MANAGEMENT =====

// Set meeting point for a trip match
exports.setMeetingPoint = catchAsync(async (req, res, next) => {
  const { matchId } = req.params;
  const { meetingPoint } = req.body;
  const userId = req.user._id.toString();

  console.log(`🎯 [MEETING POINT] Setting meeting point for match ${matchId} by user ${req.user.userName}`);

  // Find the trip match
  const tripMatch = await TripMatch.findOne({ matchId });
  if (!tripMatch) {
    return next(new AppError("Trip match not found", 404));
  }

  // Verify user is part of this match
  if (tripMatch.organizer.userId !== userId && tripMatch.companion.userId !== userId) {
    return next(new AppError("You are not part of this trip match", 403));
  }

  // Validate meeting point data
  if (!meetingPoint || !meetingPoint.location || 
      typeof meetingPoint.location.latitude !== 'number' || 
      typeof meetingPoint.location.longitude !== 'number') {
    return next(new AppError("Valid meeting point location is required", 400));
  }

  // Update meeting point
  tripMatch.meetingPoint = {
    name: meetingPoint.name || 'Meeting Point',
    description: meetingPoint.description || '',
    location: {
      latitude: meetingPoint.location.latitude,
      longitude: meetingPoint.location.longitude
    },
    type: meetingPoint.type || 'custom',
    setBy: req.user.userName,
    setAt: new Date()
  };

  await tripMatch.save();

  // Send real-time notification to the other user
  const { sendEventToUser } = require('./realtimeController');
  const otherUserId = tripMatch.organizer.userId === userId ? 
    tripMatch.companion.userId : tripMatch.organizer.userId;
  
  const eventData = {
    matchId: matchId,
    meetingPoint: tripMatch.meetingPoint,
    setByName: req.user.userName,
    message: `${req.user.userName} set the meeting point: ${meetingPoint.name}`,
    timestamp: new Date().toISOString()
  };

  sendEventToUser(otherUserId, 'meeting_point_set', eventData);

  console.log(`✅ [MEETING POINT] Meeting point set successfully for match ${matchId}`);

  res.status(200).json({
    status: "success",
    message: "Meeting point set successfully",
    data: {
      tripMatch,
      meetingPoint: tripMatch.meetingPoint
    }
  });
});

// Start live location sharing
exports.startLocationSharing = catchAsync(async (req, res, next) => {
  const { matchId } = req.params;
  const userId = req.user._id.toString();

  console.log(`📍 [LOCATION SHARING] Starting location sharing for match ${matchId} by user ${req.user.userName}`);

  // Find the trip match
  const tripMatch = await TripMatch.findOne({ matchId });
  if (!tripMatch) {
    return next(new AppError("Trip match not found", 404));
  }

  // Verify user is part of this match
  if (tripMatch.organizer.userId !== userId && tripMatch.companion.userId !== userId) {
    return next(new AppError("You are not part of this trip match", 403));
  }

  // Enable live location sharing
  tripMatch.liveLocationSharing.enabled = true;
  tripMatch.status = 'in-progress';
  
  if (!tripMatch.progression.started) {
    tripMatch.progression.started = new Date();
  }

  await tripMatch.save();

  // Send real-time notification to the other user
  const { sendEventToUser } = require('./realtimeController');
  const otherUserId = tripMatch.organizer.userId === userId ? 
    tripMatch.companion.userId : tripMatch.organizer.userId;
  
  const eventData = {
    matchId: matchId,
    startedBy: req.user.userName,
    message: `${req.user.userName} started live location sharing. Trip is now in progress!`,
    timestamp: new Date().toISOString()
  };

  sendEventToUser(otherUserId, 'trip_started', eventData);

  console.log(`✅ [LOCATION SHARING] Location sharing enabled for match ${matchId}`);

  res.status(200).json({
    status: "success",
    message: "Live location sharing started. Trip is now in progress!",
    data: {
      tripMatch,
      locationSharingEnabled: true
    }
  });
});

// Update live location during trip
exports.updateLiveLocation = catchAsync(async (req, res, next) => {
  const { matchId } = req.params;
  const { latitude, longitude } = req.body;
  const userId = req.user._id.toString();

  if (!latitude || !longitude) {
    return next(new AppError("Latitude and longitude are required", 400));
  }

  // Find the trip match
  const tripMatch = await TripMatch.findOne({ matchId });
  if (!tripMatch) {
    return next(new AppError("Trip match not found", 404));
  }

  // Verify user is part of this match and location sharing is enabled
  if (tripMatch.organizer.userId !== userId && tripMatch.companion.userId !== userId) {
    return next(new AppError("You are not part of this trip match", 403));
  }

  if (!tripMatch.liveLocationSharing.enabled) {
    return next(new AppError("Live location sharing is not enabled for this trip", 400));
  }

  // Update the appropriate user's location
  const isOrganizer = tripMatch.organizer.userId === userId;
  const locationField = isOrganizer ? 'organizerLocation' : 'companionLocation';

  tripMatch.liveLocationSharing[locationField] = {
    latitude: latitude,
    longitude: longitude,
    lastUpdated: new Date()
  };

  await tripMatch.save();

  // Send real-time location update to the other user
  const { sendEventToUser } = require('./realtimeController');
  const otherUserId = isOrganizer ? tripMatch.companion.userId : tripMatch.organizer.userId;
  
  const eventData = {
    matchId: matchId,
    userId: userId,
    userName: req.user.userName,
    location: { latitude, longitude },
    timestamp: new Date().toISOString()
  };

  sendEventToUser(otherUserId, 'location_update', eventData);

  res.status(200).json({
    status: "success",
    message: "Location updated successfully",
    data: {
      location: { latitude, longitude },
      timestamp: new Date()
    }
  });
});

// Get trip match details for coordination
exports.getTripMatchDetails = catchAsync(async (req, res, next) => {
  const { matchId } = req.params;
  const userId = req.user._id.toString();

  console.log(`📋 [MATCH DETAILS] Getting details for match ${matchId} by user ${req.user.userName}`);

  // Find the trip match
  const tripMatch = await TripMatch.findOne({ matchId });
  if (!tripMatch) {
    return next(new AppError("Trip match not found", 404));
  }

  // Verify user is part of this match
  if (tripMatch.organizer.userId !== userId && tripMatch.companion.userId !== userId) {
    return next(new AppError("You are not part of this trip match", 403));
  }

  // Get the original trip request for additional details
  const tripRequest = await TripRequest.findOne({ tripReqId: tripMatch.originalTripRequest.tripReqId });

  res.status(200).json({
    status: "success",
    data: {
      tripMatch,
      originalTripRequest: tripRequest,
      userRole: tripMatch.organizer.userId === userId ? 'organizer' : 'companion'
    }
  });
});

// Cancel trip match
exports.cancelTripMatch = catchAsync(async (req, res, next) => {
  const { matchId } = req.params;
  const { reason } = req.body;
  const userId = req.user._id.toString();

  console.log(`❌ [CANCEL TRIP] Cancelling match ${matchId} by user ${req.user.userName}`);

  // Find the trip match
  const tripMatch = await TripMatch.findOne({ matchId });
  if (!tripMatch) {
    return next(new AppError("Trip match not found", 404));
  }

  // Verify user is part of this match
  if (tripMatch.organizer.userId !== userId && tripMatch.companion.userId !== userId) {
    return next(new AppError("You are not part of this trip match", 403));
  }

  // Update trip match status
  tripMatch.status = 'cancelled';
  tripMatch.progression.cancelled = new Date();

  await tripMatch.save();

  // Send real-time notification to the other user
  const { sendEventToUser } = require('./realtimeController');
  const otherUserId = tripMatch.organizer.userId === userId ? 
    tripMatch.companion.userId : tripMatch.organizer.userId;
  
  const eventData = {
    matchId: matchId,
    cancelledBy: req.user.userName,
    reason: reason || 'No reason provided',
    message: `${req.user.userName} cancelled the trip match`,
    timestamp: new Date().toISOString()
  };

  sendEventToUser(otherUserId, 'trip_cancelled', eventData);

  console.log(`✅ [CANCEL TRIP] Trip match ${matchId} cancelled successfully`);

  res.status(200).json({
    status: "success",
    message: "Trip match cancelled successfully",
    data: {
      tripMatch,
      cancelReason: reason
    }
  });
});

// Mark user as arrived at meeting point
exports.markUserArrived = catchAsync(async (req, res, next) => {
  const { matchId } = req.params;
  const userId = req.user._id.toString();
  const { distance } = req.body; // Distance from meeting point when "Almost There" was pressed

  console.log(`📍 [ARRIVAL] User ${req.user.userName} marked as arrived for match ${matchId} (distance: ${distance}m)`);

  // Find the trip match
  const tripMatch = await TripMatch.findOne({ matchId });
  if (!tripMatch) {
    return next(new AppError("Trip match not found", 404));
  }

  // Verify user is part of this match
  if (tripMatch.organizer.userId !== userId && tripMatch.companion.userId !== userId) {
    return next(new AppError("You are not part of this trip match", 403));
  }

  // Initialize arrivedUsers array if it doesn't exist
  if (!tripMatch.arrivedUsers) {
    tripMatch.arrivedUsers = [];
  }

  // Add user to arrived list if not already there
  if (!tripMatch.arrivedUsers.includes(userId)) {
    tripMatch.arrivedUsers.push(userId);
    
    // Store arrival time
    if (!tripMatch.arrivalTimes) {
      tripMatch.arrivalTimes = new Map();
    }
    tripMatch.arrivalTimes.set(userId, new Date());
  }

  // Check if both users have arrived
  const bothArrived = tripMatch.arrivedUsers.length >= 2;
  
  if (bothArrived) {
    // Automatically start the final journey when both users arrive
    tripMatch.canStartFinalJourney = true;
    tripMatch.status = 'in-progress'; // Change from 'ready-to-start' to 'in-progress'
    tripMatch.tripStarted = true;
    tripMatch.tripStartedAt = new Date();
    tripMatch.progression.started = new Date();
    
    // Initialize startedUsers array if it doesn't exist
    if (!tripMatch.startedUsers) {
      tripMatch.startedUsers = [];
    }
    
    // Add both users to startedUsers since trip starts automatically
    const organizerUserId = tripMatch.organizer.userId;
    const companionUserId = tripMatch.companion.userId;
    
    if (!tripMatch.startedUsers.includes(organizerUserId)) {
      tripMatch.startedUsers.push(organizerUserId);
    }
    if (!tripMatch.startedUsers.includes(companionUserId)) {
      tripMatch.startedUsers.push(companionUserId);
    }
    
    console.log(`🚀 [TRIP STARTED] Final journey automatically started for match ${matchId}`);
  }

  await tripMatch.save();

  // Send real-time notification to both users
  const { sendEventToUser } = require('./realtimeController');
  const otherUserId = tripMatch.organizer.userId === userId ? 
    tripMatch.companion.userId : tripMatch.organizer.userId;
  
  const eventData = {
    matchId: matchId,
    arrivedUser: req.user.userName,
    bothArrived: bothArrived,
    canStartTrip: tripMatch.canStartFinalJourney,
    tripStarted: bothArrived, // Add this flag
    status: tripMatch.status,
    message: bothArrived 
      ? `🚀 Both users have arrived! Final journey has started automatically.`
      : `📍 ${req.user.userName} has arrived at the meeting point. Waiting for you to arrive.`,
    timestamp: new Date().toISOString()
  };

  // Send to the other user
  sendEventToUser(otherUserId, 'user_arrived', eventData);
  
  // Also send to current user so both get the update
  sendEventToUser(userId, 'user_arrived', eventData);

  console.log(`✅ [ARRIVAL] User arrival recorded for match ${matchId}. Both arrived: ${bothArrived}`);

  res.status(200).json({
    status: "success",
    message: bothArrived ? "Both users have arrived! Final journey started automatically." : "Arrival recorded. Waiting for other user.",
    data: {
      tripMatch,
      bothArrived: bothArrived,
      canStartTrip: tripMatch.canStartFinalJourney,
      tripStarted: bothArrived,
      arrivedUsers: tripMatch.arrivedUsers
    }
  });
});

// Start final journey from meeting point to destination
exports.startFinalJourney = catchAsync(async (req, res, next) => {
  const { matchId } = req.params;
  const userId = req.user._id.toString();

  console.log(`🚀 [FINAL JOURNEY] User ${req.user.userName} starting final journey for match ${matchId}`);

  // Find the trip match
  const tripMatch = await TripMatch.findOne({ matchId });
  if (!tripMatch) {
    return next(new AppError("Trip match not found", 404));
  }

  // Verify user is part of this match
  if (tripMatch.organizer.userId !== userId && tripMatch.companion.userId !== userId) {
    return next(new AppError("You are not part of this trip match", 403));
  }

  // Check if both users have arrived
  if (!tripMatch.canStartFinalJourney) {
    return next(new AppError("Both users must arrive at meeting point before starting the final journey", 400));
  }

  // Initialize startedUsers array if it doesn't exist
  if (!tripMatch.startedUsers) {
    tripMatch.startedUsers = [];
  }

  // Add user to started list if not already there
  if (!tripMatch.startedUsers.includes(userId)) {
    tripMatch.startedUsers.push(userId);
    console.log(`📍 [FINAL JOURNEY] User ${req.user.userName} marked as ready to start final journey`);
  }

  // Check if both users are ready to start
  const bothReady = tripMatch.startedUsers.length >= 2;
  
  if (bothReady && !tripMatch.tripStarted) {
    tripMatch.tripStarted = true;
    tripMatch.tripStartedAt = new Date();
    tripMatch.status = 'in-progress';
    tripMatch.progression.started = new Date();
    console.log(`🎉 [FINAL JOURNEY] Both users ready! Starting final journey for match ${matchId}`);
  }

  await tripMatch.save();

  // Send real-time notification to the other user
  const { sendEventToUser } = require('./realtimeController');
  const otherUserId = tripMatch.organizer.userId === userId ? 
    tripMatch.companion.userId : tripMatch.organizer.userId;
  
  const eventData = {
    matchId: matchId,
    startedUser: req.user.userName,
    bothReady: bothReady,
    tripStarted: tripMatch.tripStarted,
    message: bothReady 
      ? `🚀 Both users are ready! The final journey has begun. Navigate together to your destination.`
      : `✅ ${req.user.userName} is ready to start the final journey. Waiting for you to press "Start Trip".`,
    timestamp: new Date().toISOString()
  };

  sendEventToUser(otherUserId, 'final_journey_status', eventData);

  console.log(`✅ [FINAL JOURNEY] Final journey status updated for match ${matchId}. Both ready: ${bothReady}`);

  res.status(200).json({
    status: "success",
    message: bothReady ? "Final journey started! Navigate together to your destination." : "Ready to start. Waiting for your companion.",
    data: {
      tripMatch,
      bothReady: bothReady,
      tripStarted: tripMatch.tripStarted,
      startedUsers: tripMatch.startedUsers
    }
  });
});

// End trip match journey - Two-stage ending process
// End trip match journey - Two-stage ending process
exports.endTripMatch = catchAsync(async (req, res, next) => {
  const { matchId } = req.params;
  const userId = req.user._id.toString();

  console.log(`🏁 [END TRIP] User ${req.user.userName} ending trip match ${matchId}`);

  // Find the trip match
  const tripMatch = await TripMatch.findOne({ matchId });
  if (!tripMatch) {
    return next(new AppError("Trip match not found", 404));
  }

  // Verify user is part of this match
  if (tripMatch.organizer.userId !== userId && tripMatch.companion.userId !== userId) {
    return next(new AppError("You are not part of this trip match", 403));
  }

  // Check if user has already ended the trip
  if (tripMatch.endedUsers.includes(userId)) {
    return res.status(200).json({
      status: "success",
      message: "You have already ended this trip",
      data: {
        tripMatch,
        userEnded: true,
        waitingForOther: !tripMatch.tripEnded,
        bothEnded: tripMatch.tripEnded
      }
    });
  }

  // Add user to endedUsers array
  tripMatch.endedUsers.push(userId);

  // Check if both users have ended the trip
  const bothUsersEnded = tripMatch.endedUsers.length === 2;

  if (bothUsersEnded) {
    // Both users have ended - mark trip as completed
    tripMatch.status = 'completed';
    tripMatch.tripEnded = true;
    tripMatch.tripEndedAt = new Date();
    tripMatch.progression.completed = new Date();

    console.log(`🎉 [TRIP COMPLETED] Both users have ended trip ${matchId}`);
  } else {
    console.log(`⏳ [WAITING] User ${req.user.userName} ended trip, waiting for other user`);
  }
  // Check if user has already ended the trip
  if (tripMatch.endedUsers.includes(userId)) {
    return res.status(200).json({
      status: "success",
      message: "You have already ended this trip",
      data: {
        tripMatch,
        userEnded: true,
        waitingForOther: !tripMatch.tripEnded,
        bothEnded: tripMatch.tripEnded
      }
    });
  }

  // Add user to endedUsers array
  tripMatch.endedUsers.push(userId);

  // Check if both users have ended the trip
  const bothUsersEnded = tripMatch.endedUsers.length === 2;

  if (bothUsersEnded) {
    // Both users have ended - mark trip as completed
    tripMatch.status = 'completed';
    tripMatch.tripEnded = true;
    tripMatch.tripEndedAt = new Date();
    tripMatch.progression.completed = new Date();

    console.log(`🎉 [TRIP COMPLETED] Both users have ended trip ${matchId}`);
  } else {
    console.log(`⏳ [WAITING] User ${req.user.userName} ended trip, waiting for other user`);
  }

  await tripMatch.save();

  // Send real-time notification to the other user
  const { sendEventToUser } = require('./realtimeController');
  const otherUserId = tripMatch.organizer.userId === userId ? 
    tripMatch.companion.userId : tripMatch.organizer.userId;
  
  if (bothUsersEnded) {
    // Send completion notification to both users
    const completionEventData = {
      matchId: matchId,
      message: `� Trip completed! Both users have confirmed the trip has ended.`,
      timestamp: new Date().toISOString(),
      tripCompleted: true
    };

    sendEventToUser(otherUserId, 'trip_completed', completionEventData);
    sendEventToUser(userId, 'trip_completed', completionEventData);
  } else {
    // Send waiting notification to the other user
    const waitingEventData = {
      matchId: matchId,
      endedBy: req.user.userName,
      message: `${req.user.userName} has ended the trip. Waiting for you to confirm.`,
      timestamp: new Date().toISOString(),
      waitingForConfirmation: true
    };

    sendEventToUser(otherUserId, 'trip_ending_waiting', waitingEventData);
  }

  res.status(200).json({
    status: "success",
    message: bothUsersEnded 
      ? "Trip completed successfully! Both users have confirmed the trip has ended." 
      : "You have ended the trip. Waiting for your companion to confirm.",
    data: {
      tripMatch,
      userEnded: true,
      waitingForOther: !bothUsersEnded,
      bothEnded: bothUsersEnded,
      tripCompleted: bothUsersEnded
    }
  });
});

// ===== MESSAGING SYSTEM =====

// Send a message in trip match
exports.sendMessage = catchAsync(async (req, res, next) => {
  const { matchId } = req.params;
  const { message } = req.body;
  const userId = req.user._id.toString();

  console.log(`💬 [SEND MESSAGE] User ${req.user.userName} sending message to match ${matchId}`);

  // Validate message content
  if (!message || message.trim().length === 0) {
    return next(new AppError("Message content is required", 400));
  }

  if (message.length > 500) {
    return next(new AppError("Message too long. Maximum 500 characters allowed", 400));
  }

  // Find the trip match
  const tripMatch = await TripMatch.findOne({ matchId });
  if (!tripMatch) {
    return next(new AppError("Trip match not found", 404));
  }

  // Verify user is part of this match
  if (tripMatch.organizer.userId !== userId && tripMatch.companion.userId !== userId) {
    return next(new AppError("You are not part of this trip match", 403));
  }

  // Add message using the instance method
  const newMessage = tripMatch.addMessage(userId, req.user.userName, message.trim());
  await tripMatch.save();

  // Send real-time notification to the other user
  const { sendEventToUser } = require('./realtimeController');
  const otherUserId = tripMatch.organizer.userId === userId ? 
    tripMatch.companion.userId : tripMatch.organizer.userId;
  
  const eventData = {
    matchId: matchId,
    message: newMessage,
    senderName: req.user.userName,
    timestamp: new Date().toISOString()
  };

  sendEventToUser(otherUserId, 'new_message', eventData);

  console.log(`✅ [MESSAGE SENT] Message delivered for match ${matchId}`);

  res.status(201).json({
    status: "success",
    message: "Message sent successfully",
    data: {
      message: newMessage
    }
  });
});

// Get messages for trip match
exports.getMessages = catchAsync(async (req, res, next) => {
  const { matchId } = req.params;
  const userId = req.user._id.toString();
  const { lastMessageId } = req.query; // For pagination

  console.log(`📖 [GET MESSAGES] User ${req.user.userName} getting messages for match ${matchId}`);

  // Find the trip match
  const tripMatch = await TripMatch.findOne({ matchId });
  if (!tripMatch) {
    return next(new AppError("Trip match not found", 404));
  }

  // Verify user is part of this match
  if (tripMatch.organizer.userId !== userId && tripMatch.companion.userId !== userId) {
    return next(new AppError("You are not part of this trip match", 403));
  }

  // Initialize messages array if it doesn't exist (backward compatibility)
  if (!tripMatch.messages) {
    tripMatch.messages = [];
  }

  let messages = tripMatch.messages;

  // If lastMessageId is provided, only return newer messages
  if (lastMessageId) {
    const lastMessageIndex = messages.findIndex(msg => msg.messageId === lastMessageId);
    if (lastMessageIndex !== -1) {
      messages = messages.slice(lastMessageIndex + 1);
    }
  }

  // Mark messages as read by current user
  let hasNewReads = false;
  messages.forEach(message => {
    if (message.senderId !== userId) {
      const existingRead = message.readBy.find(read => read.userId === userId);
      if (!existingRead) {
        message.readBy.push({
          userId: userId,
          readAt: new Date()
        });
        hasNewReads = true;
      }
    }
  });

  // Save if we added any read receipts
  if (hasNewReads) {
    await tripMatch.save();
  }

  res.status(200).json({
    status: "success",
    data: {
      messages: messages,
      totalMessages: tripMatch.messages.length,
      hasMoreMessages: lastMessageId ? true : false // Simple implementation
    }
  });
});

// Mark message as read (alternative endpoint for explicit read marking)
exports.markMessageRead = catchAsync(async (req, res, next) => {
  const { matchId, messageId } = req.params;
  const userId = req.user._id.toString();

  // Find the trip match
  const tripMatch = await TripMatch.findOne({ matchId });
  if (!tripMatch) {
    return next(new AppError("Trip match not found", 404));
  }

  // Verify user is part of this match
  if (tripMatch.organizer.userId !== userId && tripMatch.companion.userId !== userId) {
    return next(new AppError("You are not part of this trip match", 403));
  }

  // Find the message and mark as read
  const message = tripMatch.messages.find(msg => msg.messageId === messageId);
  if (!message) {
    return next(new AppError("Message not found", 404));
  }

  // Don't mark own messages as read
  if (message.senderId === userId) {
    return res.status(200).json({
      status: "success",
      message: "Cannot mark own message as read"
    });
  }

  // Add read receipt if not already read
  const existingRead = message.readBy.find(read => read.userId === userId);
  if (!existingRead) {
    message.readBy.push({
      userId: userId,
      readAt: new Date()
    });
    await tripMatch.save();
  }

  res.status(200).json({
    status: "success",
    message: "Message marked as read"
  });
});
