const User = require("../models/userModel");
const Trip = require("../models/tripModel");
const TripRequest = require("../models/tripRequestModel");
const { uploadToCloudinary, deleteFromCloudinary } = require("../utils/fileUpload");

const AppError = require("../utils/AppError");
const catchAsync = require("../utils/catchAsync");

  exports.createTripReq = catchAsync(async (req, res, next) => {
    const { 
      user, 
      destination, 
      destinationType, 
      date, 
      time, 
      genderPreference,
      startLocation,
      destinationLocation,
      routeCoordinates,
      transportMode,
      searchDuration = 2 * 60 * 1000 // Default 2 minutes
    } = req.body;
  
    if (!user || !user.userName) {
      return next(new AppError("User name is required", 400));
    }
  
    // Find user by userName
    const existingUser = await User.findOne({ userName: user.userName });
    if (!existingUser) {
      return next(new AppError("User not found", 404));
    }
  
    // Generate trip request ID
    const tripReqId = existingUser.userName.slice(0, 3).toUpperCase() + Date.now();
  
    // Create new TripRequest using full user data
    const newTripRequest = await TripRequest.create({
      tripReqId,
      user: {
        userId: existingUser._id.toString(),
        userName: existingUser.userName,
        userImage: existingUser.profilePhoto || "default.jpg"
      },
      startingLocation: startLocation, // Use the new field name
      destination,
      destinationType,
      date,
      time,
      genderPreference,
      destinationLocation,
      routeCoordinates: routeCoordinates || [],
      transportMode,
      searchDuration,
      expiresAt: new Date(Date.now() + searchDuration),
      // Automatically set meeting point to sender's starting location
      meetingPoint: {
        latitude: startLocation?.latitude,
        longitude: startLocation?.longitude,
        address: startLocation?.address,
        name: "Starting Point",
        description: "Sender's starting location",
        type: "starting_point",
        isAutoGenerated: true
      },
      consent: {
        senderConsent: true, // Set when sender completes consent form
        noTouchAgreed: false,
        receiverConsent: false
      }
    });
  
    res.status(201).json({
      status: "success",
      data: {
        tripRequest: newTripRequest,
      },
    });
  });  

  
exports.createTrip = catchAsync(async (req, res, next) => {
  const { user, companion, consent, distanceMaintained, distancePreferred, genderPreference, imageVerification } = req.body;

  if (!user?.userName || !companion?.userName) {
    return next(new AppError("Both user and companion usernames are required", 400));
  }

  // Find user and companion by username
  const existingUser = await User.findOne({ userName: user.userName });
  if (!existingUser) return next(new AppError("User not found", 404));

  const existingCompanion = await User.findOne({ userName: companion.userName });
  if (!existingCompanion) return next(new AppError("Companion not found", 404));

  // Generate unique trip ID
  const tripId = existingUser.userName.slice(0, 3).toUpperCase() + existingCompanion.userName.slice(0, 3).toUpperCase() + Date.now();

  // Create trip
  const newTrip = await Trip.create({
    tripId,
    user: {
      userId: existingUser._id.toString(),
      userName: existingUser.userName,
      userImage: existingUser.profilePhoto || "default.jpg"
    },
    companion: {
      userId: existingCompanion._id.toString(),
      userName: existingCompanion.userName,
      userImage: existingCompanion.profilePhoto || "default.jpg"
    },
    consent,
    distanceMaintained,
    distancePreferred,
    genderPreference,
    imageVerification
  });

  res.status(201).json({
    status: "success",
    data: {
      trip: newTrip
    }
  });
});

// Update trip request with route and location data
exports.updateTripRequest = catchAsync(async (req, res, next) => {
  const { tripReqId } = req.params;
  const updateData = req.body;

  console.log('🔄 [UPDATE TRIP] Updating trip request:', tripReqId);
  console.log('🔄 [UPDATE TRIP] Update data:', JSON.stringify(updateData, null, 2));

  const tripRequest = await TripRequest.findOneAndUpdate(
    { tripReqId },
    updateData,
    { new: true, runValidators: true }
  );

  if (!tripRequest) {
    console.log('❌ [UPDATE TRIP] Trip request not found:', tripReqId);
    return next(new AppError("Trip request not found", 404));
  }

  console.log('✅ [UPDATE TRIP] Trip request updated successfully');
  console.log('📍 [UPDATE TRIP] Updated route data:', {
    destination: tripRequest.destination,
    destinationType: tripRequest.destinationType,
    hasStartLocation: !!tripRequest.startLocation,
    hasDestinationLocation: !!tripRequest.destinationLocation,
    routeCoordinatesCount: tripRequest.routeCoordinates?.length || 0,
    transportMode: tripRequest.transportMode
  });

  res.status(200).json({
    status: "success",
    data: {
      tripRequest
    }
  });
});

// Set meeting point for trip request
exports.setMeetingPoint = catchAsync(async (req, res, next) => {
  const { tripReqId } = req.params;
  const { meetingPoint } = req.body;

  const tripRequest = await TripRequest.findOneAndUpdate(
    { tripReqId },
    { 
      meetingPoint: {
        ...meetingPoint,
        isSelected: true
      }
    },
    { new: true }
  );

  if (!tripRequest) {
    return next(new AppError("Trip request not found", 404));
  }

  res.status(200).json({
    status: "success",
    data: {
      tripRequest
    }
  });
});

// Complete consent form for receiver
exports.completeReceiverConsent = catchAsync(async (req, res, next) => {
  const { tripReqId } = req.params;
  const { userId } = req.body;

  const tripRequest = await TripRequest.findOneAndUpdate(
    { tripReqId },
    { 
      'consent.receiverConsent': true,
      'consent.noTouchAgreed': true,
      'consent.consentCompletedAt': new Date()
    },
    { new: true }
  );

  if (!tripRequest) {
    return next(new AppError("Trip request not found", 404));
  }

  res.status(200).json({
    status: "success",
    message: "Consent completed successfully",
    data: {
      tripRequest
    }
  });
});

// Get active trip request for user (to maintain persistent search)
exports.getActiveRequest = catchAsync(async (req, res, next) => {
  const userId = req.user.id;

  const activeRequest = await TripRequest.findOne({
    'user.userId': userId,
    status: 'pending',
    expiresAt: { $gt: new Date() }
  });

  res.status(200).json({
    status: "success",
    data: {
      activeRequest
    }
  });
});

exports.getTripReq = catchAsync(async (req, res, next) => {
    const { tripReqId } = req.body;

    if (!tripReqId) {
        return next(new AppError("Trip Request ID is required", 400));
    }

    const tripRequest = await TripRequest.findOne({ tripReqId });

    if (!tripRequest) {
        return next(new AppError("Trip Request not found", 404));
    }

    res.status(200).json({
        status: "success",
        data: {
            tripRequest,
        },
    });
});

exports.getTrip = catchAsync(async (req, res, next) => {
    const { tripId } = req.body;

    if (!tripId) {
        return next(new AppError("Trip ID is required", 400));
    }

    const trip = await Trip.findOne({ tripId });

    if (!trip) {
        return next(new AppError("Trip not found", 404));
    }

    res.status(200).json({
        status: "success",
        data: {
            trip,
        },
    });
});

exports.uploadTripPhoto = catchAsync(async (req, res, next) => {
  if (!req.file) {
    return next(new AppError("No file uploaded", 400));
  }

  const { tripReqId } = req.params;
  if (!tripReqId) {
    return next(new AppError("Trip Request ID is required", 400));
  }

  const tripRequest = await TripRequest.findOne({ tripReqId });
  if (!tripRequest) {
    return next(new AppError("Trip Request not found", 404));
  }

  // Delete existing photo if any
  if (tripRequest.photo?.publicId) {
    await deleteFromCloudinary(tripRequest.photo.publicId);
  }

  // Upload new photo
  const uploadResult = await uploadToCloudinary(
    req.file,
    "trip-photos",
    tripRequest.user.userId
  );

  // Update trip request with new photo
  tripRequest.photo = uploadResult;
  await tripRequest.save();

  res.status(200).json({
    status: "success",
    message: "Photo uploaded successfully",
    data: {
      photoUrl: uploadResult.url
    }
  });
});

exports.updateTripRequestBasic = catchAsync(async (req, res, next) => {
  const { tripReqId } = req.params;
  const { destination, destinationType, date, time, genderPreference } = req.body;

  if (!tripReqId) {
    return next(new AppError("Trip Request ID is required", 400));
  }

  const tripRequest = await TripRequest.findOne({ tripReqId });
  if (!tripRequest) {
    return next(new AppError("Trip Request not found", 404));
  }

  // Update fields if provided
  if (destination) tripRequest.destination = destination;
  if (destinationType) tripRequest.destinationType = destinationType;
  if (date) tripRequest.date = date;
  if (time) tripRequest.time = time;
  if (genderPreference) tripRequest.genderPreference = genderPreference;

  await tripRequest.save();

  res.status(200).json({
    status: "success",
    message: "Trip request updated successfully",
    data: {
      tripRequest
    }
  });
});

exports.markArrived = catchAsync(async (req, res, next) => {
  const { requestId } = req.body;
  const userId = req.user._id.toString();

  if (!requestId) {
    return next(new AppError("Request ID is required", 400));
  }

  const tripRequest = await TripRequest.findById(requestId);
  if (!tripRequest) {
    return next(new AppError("Trip request not found", 404));
  }

  // Initialize arrivedUsers array if it doesn't exist
  if (!tripRequest.arrivedUsers) {
    tripRequest.arrivedUsers = [];
  }

  // Check if user already marked as arrived
  if (tripRequest.arrivedUsers.includes(userId)) {
    return res.status(200).json({
      status: "success",
      message: "Already marked as arrived"
    });
  }

  // Add user to arrived list
  tripRequest.arrivedUsers.push(userId);

  // Check if both users have arrived (sender and receiver)
  const allUsersArrived = tripRequest.arrivedUsers.includes(tripRequest.user.userId) && 
                          tripRequest.receiverConsent && 
                          tripRequest.arrivedUsers.includes(tripRequest.receiverConsent.receiverId);

  if (allUsersArrived) {
    tripRequest.canStartFinalJourney = true;
  }

  await tripRequest.save();

  res.status(200).json({
    status: "success",
    message: allUsersArrived ? "Both users arrived! Ready to start final journey." : "Arrival marked successfully",
    data: {
      arrivedUsers: tripRequest.arrivedUsers,
      canStartFinalJourney: tripRequest.canStartFinalJourney
    }
  });
});

exports.startTrip = catchAsync(async (req, res, next) => {
  const { requestId } = req.body;
  const userId = req.user._id.toString();

  if (!requestId) {
    return next(new AppError("Request ID is required", 400));
  }

  const tripRequest = await TripRequest.findById(requestId);
  if (!tripRequest) {
    return next(new AppError("Trip request not found", 404));
  }

  // Initialize startedUsers array if it doesn't exist
  if (!tripRequest.startedUsers) {
    tripRequest.startedUsers = [];
  }

  // Check if user already marked as started
  if (tripRequest.startedUsers.includes(userId)) {
    return res.status(200).json({
      status: "success",
      message: "Already marked as started",
      data: { bothUsersReady: tripRequest.tripStarted }
    });
  }

  // Add user to started list
  tripRequest.startedUsers.push(userId);

  // Check if both users are ready to start (sender and receiver)
  const bothUsersReady = tripRequest.startedUsers.includes(tripRequest.user.userId) && 
                        tripRequest.receiverConsent && 
                        tripRequest.startedUsers.includes(tripRequest.receiverConsent.receiverId);

  if (bothUsersReady) {
    tripRequest.tripStarted = true;
    tripRequest.tripStartedAt = new Date();
  }

  await tripRequest.save();

  res.status(200).json({
    status: "success",
    message: bothUsersReady ? "Both users ready! Trip started!" : "Ready to start trip",
    data: {
      startedUsers: tripRequest.startedUsers,
      bothUsersReady: tripRequest.tripStarted
    }
  });
});

exports.cancelTrip = catchAsync(async (req, res, next) => {
  const { requestId } = req.body;
  const userId = req.user._id.toString();

  if (!requestId) {
    return next(new AppError("Request ID is required", 400));
  }

  const tripRequest = await TripRequest.findById(requestId);
  if (!tripRequest) {
    return next(new AppError("Trip request not found", 404));
  }

  // Check if user is part of this trip
  const isOrganizerOrCompanion = tripRequest.user.userId === userId || 
                                 (tripRequest.receiverConsent && tripRequest.receiverConsent.receiverId === userId);
  
  if (!isOrganizerOrCompanion) {
    return next(new AppError("You are not authorized to cancel this trip", 403));
  }

  // Update status to cancelled
  tripRequest.status = 'cancelled';
  tripRequest.cancelledBy = userId;
  tripRequest.cancelledAt = new Date();

  await tripRequest.save();

  res.status(200).json({
    status: "success",
    message: "Trip cancelled successfully"
  });
});

exports.endTrip = catchAsync(async (req, res, next) => {
  const { requestId } = req.body;
  const userId = req.user._id.toString();

  if (!requestId) {
    return next(new AppError("Request ID is required", 400));
  }

  const tripRequest = await TripRequest.findById(requestId);
  if (!tripRequest) {
    return next(new AppError("Trip request not found", 404));
  }

  // Check if user is part of this trip
  const isOrganizerOrCompanion = tripRequest.user.userId === userId || 
                                 (tripRequest.receiverConsent && tripRequest.receiverConsent.receiverId === userId);
  
  if (!isOrganizerOrCompanion) {
    return next(new AppError("You are not authorized to end this trip", 403));
  }

  // Update status to completed
  tripRequest.status = 'completed';
  tripRequest.completedAt = new Date();

  await tripRequest.save();

  res.status(200).json({
    status: "success",
    message: "Trip completed successfully"
  });
});

exports.expireRequest = catchAsync(async (req, res, next) => {
  const { tripReqId } = req.params;
  const userId = req.user._id.toString();

  if (!tripReqId) {
    return next(new AppError("Trip Request ID is required", 400));
  }

  const tripRequest = await TripRequest.findOne({ tripReqId });
  if (!tripRequest) {
    return next(new AppError("Trip request not found", 404));
  }

  // Only the sender can expire their own request
  if (tripRequest.user.userId !== userId) {
    return next(new AppError("You can only expire your own requests", 403));
  }

  // Only expire if still pending
  if (tripRequest.status === 'pending') {
    tripRequest.status = 'expired';
    await tripRequest.save();

    res.status(200).json({
      status: "success",
      message: "Trip request expired successfully"
    });
  } else {
    res.status(200).json({
      status: "success", 
      message: `Request already ${tripRequest.status}`
    });
  }
});

// Update arrival status for navigation
exports.updateArrival = catchAsync(async (req, res, next) => {
  const { matchId, userRole, arrivedAt } = req.body;
  const userId = req.user._id.toString();

  console.log(`🚶‍♀️ [ARRIVAL] User ${userId} (${userRole}) arrived at meeting point for match ${matchId}`);

  const TripMatch = require("../models/tripMatchModel");
  const tripMatch = await TripMatch.findOne({ matchId });
  
  if (!tripMatch) {
    return next(new AppError("Trip match not found", 404));
  }

  // Verify user is part of this match
  const isAuthorized = tripMatch.organizer.userId === userId || tripMatch.companion.userId === userId;
  if (!isAuthorized) {
    return next(new AppError("Not authorized for this trip match", 403));
  }

  // Update arrival status
  if (userRole === 'organizer') {
    tripMatch.progression.organizerArrived = new Date(arrivedAt);
  } else {
    tripMatch.progression.companionArrived = new Date(arrivedAt);
  }

  // If both arrived, mark as meeting
  if (tripMatch.progression.organizerArrived && tripMatch.progression.companionArrived) {
    tripMatch.status = 'meeting';
    console.log(`👥 [MEETING] Both users arrived for match ${matchId}`);
  }

  await tripMatch.save();

  res.status(200).json({
    status: "success",
    message: "Arrival updated successfully",
    data: {
      match: tripMatch
    }
  });
});

// Complete trip match
exports.completeMatch = catchAsync(async (req, res, next) => {
  const { matchId, completedBy } = req.body;
  const userId = req.user._id.toString();

  console.log(`✅ [COMPLETE] User ${userId} (${completedBy}) completing match ${matchId}`);

  const TripMatch = require("../models/tripMatchModel");
  const tripMatch = await TripMatch.findOne({ matchId });
  
  if (!tripMatch) {
    return next(new AppError("Trip match not found", 404));
  }

  // Verify user is part of this match
  const isAuthorized = tripMatch.organizer.userId === userId || tripMatch.companion.userId === userId;
  if (!isAuthorized) {
    return next(new AppError("Not authorized for this trip match", 403));
  }

  // Mark as completed
  tripMatch.status = 'completed';
  tripMatch.progression.completed = new Date();
  
  await tripMatch.save();

  // Also update the original trip request
  const tripRequest = await TripRequest.findOne({ tripReqId: tripMatch.originalTripRequest.tripReqId });
  if (tripRequest) {
    tripRequest.status = 'completed';
    tripRequest.completedAt = new Date();
    await tripRequest.save();
  }

  console.log(`🎉 [COMPLETED] Match ${matchId} successfully completed`);

  res.status(200).json({
    status: "success",
    message: "Trip completed successfully",
    data: {
      match: tripMatch
    }
  });
});
